version: "3.7"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
    - 3306:3306
    volumes:
    - mysql-vol:/var/lib/mysql

volumes:
  mysql-vol: